### ISSUE TITLE
ObeliskIchimokuZEMV1 has an issue using min and max so it reads future data. Can you fix please? Would help.

### ISSUE THREAD

**Issue by Andy477** [brookmiles/freqtrade-stuff#5]
Hi,
I found an issue with your code of ObeliskIchimokuZEMV1,
it uses future data from the df because of .min() and .max(),
this makes the strategy results look really good for backtest with a 3523114.83% return from 01-01-2021 to 01-02-2021.
It looks like a great strategy and gives you good results, but is unrealistic.
Thanks.

**Comment by brookmiles** [comment]
The only use of min/max is here:

```python
        dataframe.loc[:, 'cloud_top'] = dataframe.loc[:, ['senkou_a', 'senkou_b']].max(axis=1)
        dataframe.loc[:, 'cloud_bottom'] = dataframe.loc[:, ['senkou_a', 'senkou_b']].min(axis=1)
```

note that `axis=1` is used, which causes the `min()` and `max()` operations to operate per candle of the time series, not across different candles.  for each candle, we find the min and max between the two senkou values for that tick only.  

This might help explain the difference:
https://stackoverflow.com/questions/25773245/ambiguity-in-pandas-dataframe-numpy-array-axis-definition/25774395#25774395

It may help to confirm this behaviour by graphing the values. I could be wrong... if you still believe the code is incorrect then please provide further details.

**Comment by Andy477** [comment]
Hi,
Thanks for this information.
